### ISSUE TITLE
Inconsistent parsing of arrays with dot-notation when argument order is switched

### ISSUE THREAD

**Issue by elsbree** [yargs/yargs-parser#101]
The way an array argument is parsed changes depending on whether I parse `--config.compression=store --config ./electron.config.json` vs. `--config ./electron.config.json --config.compression=store`

When I run:
```
var argv = require("yargs-parser")('--config.compression=store --config ./electron.config.json')
```

The value of `argv.compression` is
```json
[
  {
    "compression": "store"
  },
  "./electron.config.json"
]
```

But when I swap the arguments and run:
```
var argv = require("yargs-parser")('--config ./electron.config.json --config.compression=store')
```

The value of `argv.compression` is
```json
"\"./electron.config.json\""
```

I would expect them both to equal the result of the first command. Is there a reason for this, or is it a bug?

**Comment by bcoe** [comment]
@elsbree this definitely feels like a bug! thanks for reporting. If you have any interested in fixing this yourself, feel free to join our [community slack](http://devtoolscommunity.herokuapp.com/). And I'd be happy to give direction.

Either way we'll hopefully fix this for you relatively soon as we work through our backlog of issues.

**Comment by elsbree** [comment]
Thanks! I'm working on a PR now.
