### ISSUE TITLE
Positional argument, build, and argument separator behavior

### ISSUE THREAD

**Issue by fvilers** [yargs/yargs-parser#112]
Hi!

I'm using yargs to build a CLI. The CLI is made up of commands. The application is initialized like this:
```
import yargs from 'yargs';

yargs
  .commandDir('cmds')
  .demandCommand()
  .help()
  .argv;
```

The cmds directory contains various commands and one of them has a positional argument that should be treated as string as it is sometimes composed only by numbers, it must remains a string.

Here's how the command is written:
```
export const command = 'setup <client_id> <api_key>';
export const builder = yargs => yargs.string('client_id');
export const handler = setup;
```

Here's the odd behavior, client_id is coerced as string or as number depending on how the application is executed:
```
$ npx babel-node ./src setup 012 test
client_id 12
$ npx babel-node ./src -- setup 012 test
client_id 012
```

Using babel-node doesn't change anything, after being transpiled to ES5, the issue remains. I don't want my user to have to use the argument separator. What can I do better? Is it a bug in yargs?

Thanks in advance,
Fabian

**Comment by bcoe** [comment]
@fvilers 👋hey, sorry for the slow reply (tldr; my 2018 has been hell). Are you still bumping into this issue, I seem to recall patching this behavior relatively recently.

`--` turns off parsing, so I'm not shocked that you see different output when executing in this manner. If you are still running into this issue, perhaps you could add a failing test? and we'll work on getting things patched.

**Comment by fvilers** [comment]
Hi! Thanks for the comment, I'm currently not working anymore on the project involved with this issue. I'll come back here if I get it again on another one.

**Comment by bcoe** [comment]
👍 sounds good, closing until future date.
