### ISSUE TITLE
Arrays doesn't seem to work

### ISSUE THREAD

**Issue by miriti** [yargs/yargs-parser#113]
Or am I missing something?

Here is my `index.js` file:

```js
const argv = require("yargs-parser")(process.argv.slice(2));
console.log(argv);
```

Tests:

`$ node index.js -a 1 2 3`
Yields: 
`{ _: [ 2, 3 ], a: 1 }`

`$ node index.js -a 1 2 -a 3`
Yields: 
`{ _: [ 2 ], a: [ 1, 3 ] }`

I thought maybe it is an expected behavior but then I tried example from the readme:
`$ node index.js -x 1 2 -x 3 4`
Result:
`{ _: [ 2, 4 ], x: [ 1, 3 ] }`
When it should be `{ _: [], x: [1, 2, 3, 4] }` according to the [documentation](https://github.com/yargs/yargs-parser#flatten-duplicate-arrays). :thinking: 

What can be the problem?

node v9.4.0
yargs-parser v8.1.0

**Comment by nexdrew** [comment]
Hi, thanks for the question.

In order for yargs-parser to treat multiple values  after a flag as an array, you have to tell it which keys to expect, like so:

```js
const parse = require('yargs-parser')
const argv = parse(process.argv.slice(2), { array: ['a', 'x'] })
console.log(argv)
```

Note the object passed as the 2nd argument to `parse`.

Give that a shot and let us know if it does the trick.

**Comment by miriti** [comment]
It works! Thanks.
Of course it would be great to have arrays without explicitly declaring options but I understand the problem with ambiguity.

**Comment by nexdrew** [comment]
Arrays _do_ work implicitly, but only if the flag is repeated for every value, e.g. `-a one -a two -a three`. The disambiguation is only required to support multiple values after a single flag or to wrap a single value in an array.

If you don't have any other questions, is it ok to close this issue?

**Comment by miriti** [comment]
> If you don't have any other questions, is it ok to close this issue?
Sure. 
Thanks!
