### ISSUE TITLE
Disabling "flatten-duplicate-arrays" leads to unexpected results

### ISSUE THREAD

**Issue by FM-96** [yargs/yargs-parser#115]
Calling this example code:
```javascript
const yargsParser = require('yargs-parser');

const argv = yargsParser(process.argv.slice(2), {
	array: ['arr'],
	configuration: {
		'flatten-duplicate-arrays': false,
	},
});

console.log(JSON.stringify(argv, null, 2));
```
with these arguments:

`node example.js --arr One Two Three --arr Four Five Six --arr Seven Eight Nine --arr Ten Eleven Twelve`

I would expect the following output:
```json
{
  "_": [],
  "arr": [
    [
      "One",
      "Two",
      "Three"
    ],
    [
      "Four",
      "Five",
      "Six"
    ],
    [
      "Seven",
      "Eight",
      "Nine"
    ],
    [
      "Ten",
      "Eleven",
      "Twelve"
    ]
  ]
}
```
However, instead I get this output:
```json
{
  "_": [],
  "arr": [
    [
      [
        [
          "One",
          "Two",
          "Three"
        ],
        [
          "Four",
          "Five",
          "Six"
        ]
      ],
      [
        "Seven",
        "Eight",
        "Nine"
      ]
    ],
    [
      "Ten",
      "Eleven",
      "Twelve"
    ]
  ]
}
```

This doesn't seem right to me. Is this the expected behaviour? (If so, it is not apparent from the documentation, in my opinion.)

**Comment by bcoe** [comment]
@FM-96 I agree, this behavior seems incorrect to me. Would you be interested in submitting a failing test for this issue? I'd love help digging into a fix if you have time, and feel like contributing to the project.

**Comment by FM-96** [comment]
Sorry for taking so long to get back to you.

I would be interested, but I don't have the time right now, and I probably won't have time for a few more months.

However, if this is still needed after that, I'd be happy to help!
