### ISSUE TITLE
Processing of boolean options may give unexpected results

### ISSUE THREAD

**Issue by plroebuck** [yargs/yargs-parser#117]
Reopened yargs/yargs#1077 here, per @bcoe's request.

**Comment by plroebuck** [comment]
@bcoe > It's always been the behavior of boolean that you can provide a false or true string, and that providing something other than these accepted values is undefined behavior (defaulting to false in most cases for this undefined behavior seems pretty reasonable to me). I'm certainly willing to have a discussion about changing this behavior mind you.

In the original issue, I provided a listing where I marked several cases where `bin/testme` was not processed as expected based on the provided documentation. Some of those were already pointed out by @Richie765. Several I really think are worthy of a throw, as I would rather get an error up front than unexpected defaults based on undefined behavior.

**Comment by plroebuck** [comment]
@bcoe, was there a means via `.implies()` to make giving a boolean argument and its opposite illegal?
```coffee
argv = yargs
  .options(config.options)
  .implies({
    'sorted': '--no-sorted'
  })
  .argv
```

For example, given the above:
```sh
$ myapp --sorted --no-sorted
Error: options 'sorted' and 'no-sorted' are mutually exclusive
$ echo $?
1
```

**Comment by bcoe** [comment]
@plroebuck 👋thanks for opening this issue. If you're interested, please take a stab at implementing some of the behavior you described in https://github.com/yargs/yargs/issues/1077. It seems like you've researched this problem fairly throughly, and I'm not opposed to making some of the changes discussed.

I wonder if we could split the changes across a few pull requests however.

**Comment by bcoe** [comment]
@plroebuck there have been quite a few changes to parsing behavior, as it relates to edge-cases like you describe in the original issue in yargs.

If there are any issues you're still bumping into, let's open some new issues on a case by case basis for the specific behavior we'd like to fix (yargs/yargs#1077 describes a bunch of different parsing goals, it would be easier if we can identify a few concrete changes we'd like to make).

**Comment by jmm** [comment]
Hello @bcoe, re: [this comment](https://github.com/yargs/yargs/issues/1077#issuecomment-370269542):

> It's always been the behavior of boolean that you can provide a `false` or `true` string, and that providing something other than these accepted values is undefined behavior (defaulting to `false` in most cases for this undefined behavior seems pretty reasonable to me). I'm certainly willing to have a discussion about changing this behavior mind you.

That seems dangerous to me.

Consider that you have a boolean option `--safe-mode` that you want to default to `true` and require explicit opt-out (e.g. `--safe-mode=false`). It doesn't seem like a good idea to me that this evaluates to `false` (yargs@17.3.1):

```js
yargs(
  "--safe-mode=tru"
)
.boolean("safe-mode")
.default("safe-mode", true)
.argv
.safeMode
```

To get what I'd consider safe behavior would require using a different name and polarity (e.g. `--dangerous-mode` defaulting to `false`).

If it's going to proceed at all in that case, and there's a default value defined, it seems like it would be safer to use the default value rather than `false`.

I think the behavior that defaults random values to `false` would be better as an option that requires opting into.

**Comment by plroebuck** [comment]
You can't use the default value because another is given. Nor can you reverse the option's polarity and think the problem can't occur.

The original `bin/testme` noted expected results for each input. For the case above, it should have thrown an `IllegalArgumentError` (or just `Error` if not already subclassed) because `'tru' is invalid. After processing the given cmdline raw string, a Yargs `boolean` *should* be `[true|false]`. This could be handled using a `switch-case` for each desired value with `default-case throw`.
