### ISSUE TITLE
odd behavior of narg:2 versus duplicate-arguments-array:false

### ISSUE THREAD

**Issue by starpit** [yargs/yargs-parser#118]
```
const P = require('yargs-parser')
P('foo -p x y', { narg: { p: 2 } })
{ _: [ 'foo' ], p: [ 'x', 'y' ] }
```

i.e. this results in the expected `{x:'y'}` binding.

whereas:
```
P('foo -p x y', { narg: { p: 2 }, configuration: {  'duplicate-arguments-array': false } })
{ _: [ 'foo' ], p: 'y' }
```

which seems buggy, and contrary to the documentation. i would expect the resulting binding to be the same in both cases.

**Comment by bcoe** [comment]
@starpit this does seem incorrect to me; definitely feels like `duplicate-arguments-array` is interfering with `nargs`. If you have any more cycles to dig into this, I would happily accept a patch.

Otherwise I've labeled this as a bug and hopefully we can dig into it soon.
