### ISSUE TITLE
Only match negated booleans for bool options that exist

### ISSUE THREAD

**Issue by Alxandr** [yargs/yargs-parser#124]
I have a `--no-install` argument I pass in to a script to disable installing, using the following option:

```js
option('no-install', {
    alias: 'n',
    default: false,
    description: "Don't run install first",
    type: 'boolean',
  })
```

However, instead of giving me `noInstall: true` as I would expect, I get `install: false` and `noInstall: false`. This happens even though I have not defined a option called `install`. IMHO there are two things wrong with this: First, the negated bool test has higher precedence then matching against an existing option, and secondly it's perfectly happy to accept `--no-foo-bar` even if I have not configured that as an option. If the second one is a requirement for some reason (because we want to allow for arbitrary options), at least maybe move the test after checking if it's a configured option?

**Comment by bcoe** [comment]
@Alxandr I recommend not configuring options with the `no-` prefix, if you plan on supporting negation. Instead I'd configure the option `install` with the default value `true`. If this doesn't quite do the trick for you, I recommend disabling boolean prefixes like so:

```js
var parsed = parser(['--no-dice'], {
  configuration: {
    'boolean-negation': false
  }
})
```

☝️ this will give you the flexibility to configure the option the way you're thinking.
