### ISSUE TITLE
is this repository still maintained?

### ISSUE THREAD

**Issue by iilei** [yargs/yargs-parser#133]
I wonder if it makes sense to contribute to this repository anymore as there are quite a few pull requests waiting for response ofthe maintainers for months (including two pull requests by myself).

@bcoe do you need support with maintaining this repository?

**Comment by bcoe** [comment]
@iilei I'm always happy to have support maintaining a project. I wouldn't call this repo dead, it just isn't quite top of mind for me compared to the top level yargs repo.

why don't you join [this slack](http://devtoolscommunity.herokuapp.com/) and we can start working together to land some of these open pull requests?
