### ISSUE TITLE
Default value should be used when the flag is specified with no value

### ISSUE THREAD

**Issue by sindresorhus** [yargs/yargs-parser#144]
Actual:

```js
yargs(['--foo'], {number: ['foo'], default: {foo: 1}});
//=> { _: [], foo: undefined }
```

Expected:

```js
yargs(['--foo'], {number: ['foo'], default: {foo: 1}});
//=> { _: [], foo: 1 }
```

Applies to `string` and `number`.

Alternatively, it could throw, since `--foo` is technically an incorrect value, but that might be too opinionated for `yargs-parser`.

**Comment by bcoe** [comment]
@sindresorhus please take `+ yargs-parser@12.0.0` for a spin, it will now use default values if no right-hand side is provided to option.
