### ISSUE TITLE
`opts['--']` not working, but `opts.configuration['populate--']` does work

### ISSUE THREAD

**Issue by vjpr** [yargs/yargs-parser#148]
Either a bug or I didn't understand the config options, or wrong version.

```
opts['--']: arguments after the end-of-options flag -- will be set to the argv.['--'] array instead of being set to the argv._ array.
```

**Comment by bcoe** [comment]
@vjpr I believe this is left over documentation from an initial abandoned implementation of this feature, I've updated the documentation accordingly:

https://github.com/yargs/yargs-parser/commit/a02b1d5c55d4860e0b92f0c65158dace6c872ca7
