### ISSUE TITLE
Chops the `+` off the start of an option

### ISSUE THREAD

**Issue by chee** [yargs/yargs-parser#155]
`yargs-parser` seems to coerce things to numbers if it can, even if `number: false`. 

So I have a program that takes phone numbers as arguments, and sometimes phone numbers have a `+` at the start.

If i use `yargs`, and set `type: "string"` on that option I get `"447473474347"` instead of `"+447473474347"`.

`require("yargs-parser")("+447473474347")`  returns `{ _: [ 447473465256 ] }`

**Comment by bcoe** [comment]
👋 hey @chee, just testing things out for you; I think there might just be a slight misunderstanding about the API:

In yargs-parser, to avoid coercing into numbers simply:

```js
  // see: https://github.com/yargs/yargs-parser/issues/155
  it('should not drop leading "+" if type is string', function () {
    var s = parser([ '-s', '+1234' ], {
      string: 's'
    }).s
    s.should.be.a('string').and.equal('+1234')
  })
```

in yargs itself, you can do the following:

```js
const argv = require('./')
  .option('foo', {
    type: 'string'
   })
   .argv

console.info(argv)
```

**Comment by bcoe** [comment]
feel free to reopen with a reproduction, if these snippets of code don't do the trick for you; _but_, just tested myself and I think they'll work.

**Comment by chee** [comment]
Hi, I did use `type: 'string'` and it still chops off the leading + for me!

## program:

```js
let argv = require("yargs")
  .command(
    "hmm <phone>",
    "hmm a phone number",
    yargs =>
      yargs.positional(
        "phone",
        {type: "string"}
      )
  )
  .parse("hmm +4")

console.log(argv)
```

## output:

```js
{ _: [ 'hmm' ], '$0': '', phone: '4' }
```

<img width="545" alt="a screenshot of the above code" src="https://user-images.githubusercontent.com/178266/51822457-4ce50780-22d4-11e9-87a1-e80cdca15d33.png">


Oh, I notice it does work if i use `.option()` rather than `.positional()`.

is this where my mistake is?

**Comment by chee** [comment]
i've just seen this: https://github.com/yargs/yargs-parser/blob/a02b1d5c55d4860e0b92f0c65158dace6c872ca7/README.md#parse-numbers

**Comment by chee** [comment]
This works:

```js
require("yargs-parser")("lol +44", {
	configuration: {
		"parse-numbers": false
	}
})
```

So for now i'll set `yargs.parse-numbers` to `false` in my `package.json`.

If i do this:

```js
console.info(
	require("yargs").command({
		command: "command <phone>",
		builder: yargs => yargs.positional(
			"phone",
			{type: "string"}
		)
	}
).parse("command +4"))
```

That is, `type: "string"` in a positional, it seems to parse it as a number and then turns it into a string.

So instead of `"+4"` i get `"4"`.
