### ISSUE TITLE
"empty" array values erroring starting with v14.0.0

### ISSUE THREAD

**Issue by kellyselden** [yargs/yargs-parser#205]
I checked the changelog, but I couldn't find a match for this behaviour. I have a script on our CI server that evaluates to `--tag --tag smoke` sometimes based on the existence of a env var or not. Essentially `--tag $TAG1 --tag $TAG2`.

This worked as expected in v13.1.1, but started failing in v14.0.0 and v15.0.0 with:

```
Invalid values:
  Argument: tag, Given: , Choices: ...
```

**Comment by bcoe** [comment]
@juergba I'm guessing this is related to some of the debugging we've been doing around arrays for the past few releases, anything immediately come to mind that would have changed this behavior?

**Comment by juergba** [comment]
Yes, I have seen this issue.
TBH with this little information (I have a script [...]) I can't really help, I'm sorry.
```js
var args = parse('--tag --tag foo', {
        array: ['tag'],
        configuration: {
            'flatten-duplicate-arrays': true // false
        }
});
```
v13.1.0
- false: `{ _: [], tag: [ [], [], [ 'foo' ] ] }`
- true: `{ _: [], tag: [ 'foo' ] }`

v15.0.0
- false: `{ _: [], tag: [ [], [ 'foo' ] ] }`
- true: `{ _: [], tag: [ 'foo' ] }`

**Comment by bcoe** [comment]
@kellyselden mind providing a bit more of a reproduction, failing test would be great (if you're really bored :laughing:).

**Comment by kellyselden** [comment]
Added a test [here](https://github.com/yargs/yargs/pull/1447). I guess I should have filed the issue there in hindsight.

**Comment by juergba** [comment]
```js
var args = parse('--tag --tag foo', {
        array: ['tag'],
        default: {tag: []},
        configuration: {
            'flatten-duplicate-arrays': true // false
        }
});
```
- false: `{ _: [], tag: [ [], [ 'foo' ] ] }`
- true: `{ _: [], tag: [ [], 'foo' ] }`                              // *** bug ***

I will have a look within the next few days.
