### ISSUE TITLE
Parsing of string with space seems broken

### ISSUE THREAD

**Issue by effem** [yargs/yargs-parser#229]
Hi,

I'm using https://github.com/sindresorhus/meow as command line argument parser that uses yargs under the hood.

I've encountered a strange behaviour that i could not explain. It seems to have its root cause in the yargs-parser. Here are some minimal examples showing the behaviour:

Node Version: 10.15.3
yargs-parser version: 16.1.0
OS: Win 10
Terminal: Powershell

test.js:
```js
var argv = require('yargs-parser')(process.argv.slice(2))
console.log(argv)
```

Works as expected: 
```bash
$ node test -l 'asdf fghj rt cv'

{ _: [], l: 'asdf fghj rt cv' }
```

Line gets cut at the space:
```
$ node test -l '\"$.name\";\"$.description\";\"$.extra_config.repos\";\"$.condition $.condition_value\";\"$.time_range_seconds\";\"$.extra_config.query\";\"$.active\"'

{ _:
   [ '$.condition_value";"$.time_range_seconds";"$.extra_config.query";"$.active"' ],
  l:
   '"$.name";"$.description";"$.extra_config.repos";"$.condition' }
```

When an additional space is added (at the beginnig/end doesn't matter) the line gets parsed correctly:
```
$ node test -l ' \"$.name\";\"$.description\";\"$.extra_config.repos\";\"$.condition $.condition_value\";\"$.time_range_seconds\";\"$.extra_config.query\";\"$.active\"'

{ _: [],
  l:
   ' "$.name";"$.description";"$.extra_config.repos";"$.condition $.condition_value";"$.time_range_seconds";"$.extra_config.query";"$.active"' }
```

Is there an error on my side passing the argument or is the parsing broken?

**Comment by juergba** [comment]
I reduced the examples a little:
`node test -l '\"$.name\";\"$.condition $.condition_value\";\"$.active\"'`

yargs-parser processes `process.argv`, latter is created by the shell you are using.

test.js
```js
console.log(process.argv);
var argv = require('yargs-parser')(process.argv.slice(2))
console.log(argv)
```
output with PowerShell:
```
[
  'C:\\Program Files\\nodejs\\node.exe',
  'D:\\yargs-parser\\test',
  '-l',
  '"$.name";"$.condition',
  '$.condition_value";"$.active"'
]
{ _: [ '$.condition_value";"$.active"' ], l: '"$.name";"$.condition' }
```
output Git Bash:
```
[
  'C:\\Program Files\\nodejs\\node.exe',
  'D:\\yargs-parser\\test',
  '-l',
  '\\"$.name\\";\\"$.condition $.condition_value\\";\\"$.active\\"'
]
{
  _: [],
  l: '\\"$.name\\";\\"$.condition $.condition_value\\";\\"$.active\\"'
}
```
`process.argv` created by PowerShell is different than the one of Git Bash.
So your problem is not a bug within yargs-parser, but PowerShell specific.

**Comment by effem** [comment]
Ok, since it is a problem witht he bash environment, i have to deal with it myself. Thanks for the info!
