### ISSUE TITLE
Nargs doesn't consume dashed arguments since version 9.0.0

### ISSUE THREAD

**Issue by vadim-galeev** [yargs/yargs-parser#232]
Nargs doesn't consume dashed arguments since version 9.0.0. This [commit](https://github.com/yargs/yargs-parser/commit/60bb9b3ec2809b7b0bec2c0de9e2078d1b3f8fdb) ignores that fact that option argument can begin with dash.

So here is simple program petnames.js

```
// Parser is an instance of yargs-parser
// opts variable suggests that nargs options for "--cat" and a "--dog"  are 1
const parsed = Parser.detailed(args, opts);

if(parsed.argv.cat)
  console.log("Cat:" + parsed.argv.cat);
if(parsed.argv.dog)
  console.log("Dog:" + parsed.argv.dog);
```

Input string is:

`./petnames.js --cat "-foo" --dog bar`

Expected output is:
```
Cat:-foo
Dog:bar
```

Using yargs-parser version 9.0.2 (result is not correct):

`Dog:bar`

Using yargs-parser version 8.1.0 (result is correct):

```
Cat:-foo
Dog:bar
```

Also, [this example](https://github.com/yargs/yargs/blob/master/docs/api.md#nargskey-count) wouldn't work properly because of this bug.

**Comment by bcoe** [comment]
@vadim-galeev I suggest we add a configuration option, `nargs-eats-options`, which if set to `true` would enable the old behavior.

**Comment by vadim-galeev** [comment]
After the fix, "nargs-eats-option" works well with one-value options but still doesn't work with options which are considered as arrays.
For example, --foo is an array option:
--foo -apple banana cat
is not parsed correctly even with "nargs-eats-option=true"
