### ISSUE TITLE
Switch to typescript

### ISSUE THREAD

**Issue by mleguen** [yargs/yargs-parser#265]
Needed for yargs/yargs#1586

**Comment by QmarkC** [comment]
I would like to help with this. I reviewed yargs/yargs#1586 and the related pull requests. Based on that, I propose the first step be the initial TypeScript configuration and converting `lib/tokenize-arg-string.js` to TypeScript. This is similar to the [first step PR](https://github.com/yargs/yargs/pull/1587) for yargs/yargs#1586.

I created a draft PR (#272) with this proposed first step to make feedback/discussion a little easier for any of those changes.

Beyond the first step, is there any guidance on how to proceed?
To avoid big-bang merge requests I imagine you would want to convert `index.js` in parts to `lib/*.ts` files.
I created the following list with all the functions in `index.js` and took a first pass at grouping them together by topic/concern. Each group could be their own lib module or some you might prefer to be their own module (e.g. `is-number.ts` vs a `utils.ts` that exports `isNumber`) since yargs/yargs has a `is-promise.ts` module.

- Parser
   - Parser
   - Parser.detailed
- configuration
    - defaultConfiguration
    - checkConfiguration
    - setConfig
    - setConfigObject
    - setConfigObjects
- parse
    - parse
    - applyDefaultsAndAliases
- parse-argv
    - argv variable assignment in parse
    - isUnknownOptionAsArg
    - isUnknownOption
    - setArg
    - setPlaceholderKeys
    - applyCoercions
    - applyEnvVars
    - eatArray
    - eatNargs
    - processValue
    - maybeCoerceNumber
    - defaultValue
    - guessType
    - defaultForType
- parse-aliases
    - addNewAlias
    - combineAliases
    - checkAllAliases
    - extendAliases
- parse-flags
    - hasAnyFlag
    - hasFlagsMatching
    - hasAllShortFlags
- utils
    - isNumber
    - isUndefined
    - sanitizeKey
    - hasKey
    - setKey
    - increment

**Comment by bcoe** [comment]
If @mleguen is open to the help with the conversion, to me it seems like it would be great to have another person pitching in.

**Comment by mleguen** [comment]
Thanks @QmarkC for the help!

The approach I took (and try to hold) for yargs, is to focus only on switching to TS, and not to refactor at the same time, as it is already difficult enough to review as is.

So I would recommend keeping at the moment a single `lib/index.ts` module, and refactor it later into several modules in separate issues/PR.

**Comment by QmarkC** [comment]
Since `@types/camelcase` and `@types/decamelize` packages are no longer available, do you want to upgrade those dependencies as part of this issue?

`decamelize` from `^1.2.0` to `^3.2.0`
`camelcase` from `^5.0.0` to `^5.3.1`

**Comment by bcoe** [comment]
@QmarkC this would unfortunately have to b e a breaking change I think, because the latest versions of those libraries drop support for Node 6.

Until we take a breaking change, perhaps we can use `require` to pull those in without types? unless @mleguen has a better approach he's used.

**Comment by QmarkC** [comment]
@bcoe The versions listed are the last before they dropped support for Node 6. The upgrades are not needed after all. The `camelcase` package has a declaration file and I can add one for `decamelize`. I'll follow the same pattern in yargs to add it at `lib/typings/decamelize.d.ts`.

We can import them like so: `import camelCase = require('camelcase')` but I'll have to move them below the other import statements. If you would prefer `import camelCase from 'camelcase` then `esModuleInterop` and `allowSyntheticDefaultImports` need to be enabled in the tsconfig `compilerOptions`.

**Comment by mleguen** [comment]
I'd rather we stick to `import camelCase = require('camelcase')`, personally.

**Comment by bcoe** [comment]
@QmarkC as long as those versions have both TypeScript and the definitions upgrading sounds great 👍

**Comment by QmarkC** [comment]
@bcoe The current semver for `camelcase`, `^5.0.0`, already matches `5.3.1` so no change there. The package size was unchanged (19.3 kB, unpacked: 77.6 kB) after upgrading `decamelize` to `^3.2.0`.

**Comment by QmarkC** [comment]
I've been working on switching the rest of yargs-parser to TypeScript. It's pretty much done, mainly just waiting on the couple related open PRs. I did want to get some feedback on a few items while waiting on that.

Current Arguments interface:
```ts
interface Arguments {
  /** Non-option arguments */
  _: string[];
  /** The script name or node command */
  $0: string;
  /** All remaining options */
  [argName: string]: any;
}
```
- `Arguments['_']` seems like it should be `(string | number)[]` at least when `configuration['unknown-options-as-args'] === true`, see test at [L3113](https://github.com/yargs/yargs-parser/blob/master/test/yargs-parser.js#L3113-L3124) and [L3139](https://github.com/yargs/yargs-parser/blob/master/test/yargs-parser.js#L3139-L3154).
- `Arguments['$0']` - the script name doesn't seem to be required as `yargs-parser` never sets this. This is set by `yargs` after calling the parser, see [L1111](https://github.com/yargs/yargs/blob/master/yargs.js#L1111). Leaving it as is doesn't seem to hurt anything but I thought I would point this out to see if it should be removed or marked as optional.

There are a few options not covered by the existing types that I wanted to confirm types for:
- [`configObjects`](https://github.com/yargs/yargs-parser/blob/master/index.js#L35): `Array<{ [key: string]: any }>`. Example in README: `{configObjects: [{'x': 5, 'y': 33}, {'z': 44}]}`.
- [`__`](https://github.com/yargs/yargs-parser/blob/master/index.js#L42):  i18n handler, defaults to util.format. Use same as util.format? `(format: any, ...param: any[]) => string`. `yargs` passes `y18n.__` which is `(str: string, arg1?: string, arg2?: string, arg3?: string): string` so the utils.format interface works for that too.
- [`key`](https://github.com/yargs/yargs-parser/blob/master/index.js#L127): I didn't see any examples of the key option being used in the tests. Seems to be used as defaults for aliases lookup table. I can tell it's a string indexed object and opts.default is also passed to `extendAliases` so use same as default option `{ [key: string]: any }`?

**Comment by mleguen** [comment]
I meet the same kind of problems with @types/yargs-parser in yargs/yargs#1586: it looks like they were not written to match yargs-parser js code (or even use it from typescript), but rather as a submodule of @types/yargs.

So I would suggest not to rely to much on the existing @types/yargs.

**Comment by mleguen** [comment]
Here are [the yargs-parser typings I am using at the moment in yargs](https://github.com/yargs/yargs/blob/67eab27726f19ac4852aa178ce35dbf882e76fd6/lib/typings/yargs-parser.d.ts), but they still may include incorrect or incomplete types. The "source of truth" must be yargs-parser js code.

**Comment by bcoe** [comment]
this work is done \o/
