### ISSUE TITLE
Updations to serialize-javascript 

### ISSUE THREAD

**Issue by iyash1** [yargs/yargs-parser#297]
In my recent project, it was highlighted the serialize-javascript was susceptible to Prototype Pollution vulnerability and requires a minimum of serialize-javascript@3.1.0 or 4.0.0. 

Kindly let me know when do you plan to update the underlying dependencies, or any help in how to update and mitigate ourselves is also much appreciated. Thank you.

**Comment by bcoe** [comment]
👋 @iyash1 the latest versions of `yargs-parser` and [serialize-javsscript](https://github.com/yahoo/serialize-javascript) have already been patched for the security warning you are reporting I believe.

Make sure you have updated to the latest version of each library, and if you're using  a `package-lock.json`  also run `npm audit fix`.
