### ISSUE TITLE
Boolean default value coercion

### ISSUE THREAD

**Issue by Eomm** [yargs/yargs-parser#301]
I didn't found another issue about this example:
when a boolean has a default value that is not a boolean, the type is not coerced from v14 to the last one.

Is this the intended behaviour or could it be a bug?

```
var yargsParser = require("yargs-parser")

yargsParser(['--use-default'], {
    boolean: ['bool'],
    default: { bool: 'false' }
})

// v13 output:
// Object {_: [], bool: false, use-default: true, useDefault: true}

// from v14 output:
// Object {_: [], bool: "false", use-default: true, useDefault: true}
// if I set "42"
// Object {_: [], bool: 42, use-default: true, useDefault: true}
```

https://runkit.com/embed/bbdymbdxa7bc

---

The use case is storing some defaults value in the `process.env` that are plain string and injecting them as default

**Comment by bcoe** [comment]
@Eomm try this:

```
default: { bool: false }
```

The defaults for a typed option, like a `number`, `boolean`, or `string`, should be of the same type as the option 👍

**Comment by Eomm** [comment]
Thks, I read the linked issue and it seems the desidered behavior

Closing per duplicate of #143
