### ISSUE TITLE
Unable to use internal types (like Arguments, Options) 

### ISSUE THREAD

**Issue by npenin** [yargs/yargs-parser#313]
The way the current definition file is built prevents any usage of the internal types. Why not leveraging the default export (and adapt yargs-parser accordingly) ?

**Comment by bcoe** [comment]
@npenin I would like to avoid changing the API surface of yargs-parser, which is used by `>1000` other libraries, for the benefit of type exports. Unfortunately, in CJS, the default export ends up making a clunky API surface.

What you should be able to do is pull in the types from `build/lib/yargs-parser-types.d.ts`, which are the types used by the ESM version of the module -- perhaps we could make this export more obvious.

**Comment by npenin** [comment]
it used to be available, but when I upgraded to the latest version, I lost them.

**Comment by bcoe** [comment]
@npenin yes, it was determined to be a mistake to release the types in the lat major version as it broke `@types/yargs` and `@types/yargs-parser`. I endorse these as the types that folks should consider using, and it's not currently a goal of the project to ship types -- it creates too much confusion with there being other widely used types available on DefinitelyTyped.

**Comment by bcoe** [comment]
The types are here:

https://www.npmjs.com/package/@types/yargs-parser
https://www.npmjs.com/package/@types/yargs

I'm very supportive of us actively documenting these options in `yargs` and `yargs-parser`, and making sure we file patches with the upstream types to make sure they're relevant to the current state of the library.
