### ISSUE TITLE
Release 13.1.2 is not tagged

### ISSUE THREAD

**Issue by cfra** [yargs/yargs-parser#320]
[npm](https://www.npmjs.com/package/yargs-parser) shows there is a release 13.1.2.

However, this release is not tagged in the git.

Where can I find the source code and history for that release?

**Comment by bcoe** [comment]
It's not common practice for us to release versions of the library that go back this many versions, which is why it was not tagged. It was released from this branch:

https://github.com/yargs/yargs-parser/compare/13.x.x
