### ISSUE TITLE
env() removes capitalization from camel case variable names

### ISSUE THREAD

**Issue by pownkel** [yargs/yargs-parser#345]
In the update to v16, it looks like the behavior of env() changed to convert all env variable names to lowercase. Here's an example to illustrate:

```
process.env.camelCaseArg = 'value';
process.env.lowercasearg = 'value';

const envArgs = yargs().env().argv;

console.log(`lower case: ${envArgs.lowercasearg}`);
console.log(`camel case: ${envArgs.camelCaseArg}`);
console.log(`camel case variable with lower case name: ${envArgs.camelcasearg}`);

```

Running this on v15.4.0 prints
```
lower case: value
camel case: value
camel case variable with lower case name: undefined
```
While in v16.0.0 and later, the same code prints
```
lower case: value
camel case: undefined
camel case variable with lower case name: value

```
Updating to v16 broke some of our code as our camel case env variables were no longer found under their original names. I'm not sure whether the change was intentional, but the [API documentation for .env()](https://github.com/yargs/yargs/blob/master/docs/api.md#envprefix) still shows camel case env variable names in the argv object, which is misleading.

**Comment by bcoe** [comment]
@pitgrap @pownkel thank you for the bug report, I'm pretty sure this will end up being related to my reimplementing our camel case logic in v16 -- if you get a chance to dig into it, patches are very much welcome.

**Comment by pitgrap** [comment]
@bcoe can you give me a code pointer? I tried to find the PR, which introduced this bug, but gave up after 10min search. :-/

**Comment by bcoe** [comment]
@pitgrap I implemented camel-case, and de-camel-case here:

https://github.com/yargs/yargs-parser/blob/master/lib/string-utils.ts#L26

When I ported the library to ESM.

**Comment by Ivan-Strahovsky** [comment]
@bcoe I have fix in my local branch, how can I open PR for to review?

**Comment by bcoe** [comment]
this should be fixed in the latest release.
