### ISSUE TITLE
Add "ISC License" term/label explicitly in LICENSE.txt

### ISSUE THREAD

**Issue by SoheilSaif** [yargs/yargs-parser#357]
Would you please add "ISC License" in LICENSE.txt file explicitly? 
As an organisation, we use your library and our license team and the tool they use doesn't access the library license as **ISC License** and marked it as "Suspected ISC". Adding the term explicitly will help us to use the library and pass the policy checks. 

**ISC License
Copyright (c) 2016, Internet Systems Consortium, Inc. ("ISC")**

**Comment by shadowspawn** [comment]
The underlying license does not include a title:
- https://www.isc.org/licenses/
- https://opensource.org/license/isc-license-txt/

Although one does sometime appear:
- https://choosealicense.com/licenses/isc/
- https://en.wikipedia.org/wiki/ISC_license

This issue has not had any activity or upvotes in a couple of years. Is this still an issue with the library you are using?

In the absence of definite benefit, I would rather just leave alone the license!

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.
