### ISSUE TITLE
License headers for the source files

### ISSUE THREAD

**Issue by jkrems** [yargs/yargs-parser#369]
We use automatic extraction of license headers via JSC when bundling code. This is based on license information in the source files like this:

```ts
/**
 * @license
 * Copyright (c) 2016, Contributors
 * SPDX-License-Identifier: ISC
 */
```

Would you accept a PR that adds these kinds of comments to the existing source files in the repo?

**Comment by bcoe** [comment]
@jkrems would happily accept a PR.
