### ISSUE TITLE
About the use of greedy-arrays

### ISSUE THREAD

**Issue by proto1994** [yargs/yargs-parser#372]
node: 12.14.1
yargs-parser: 20.2.7

`
const command = argParser(process.argv.slice(2), {
  configuration: { 
    'greedy-arrays': true,
  }
})

console.log(command);
node cli.js --a aa bb  // { _: [ 'bb' ], c: 'aa' } 
`

when I use greedy-array, The result of this output is  { _: [ 'bb' ], c: 'aa' }

how can I get this result   { _: [ ], c: [ 'aa', 'bb'] } ?

**Comment by ArthurKa** [comment]
There is no 'c' in command line.

**Comment by banli17** [comment]
how resolve?
