### ISSUE TITLE
allow configuration to be passed into yargs-parser

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs-parser#4]
By default `yargs-parser` and `yargs` load configuration from a `yargs` stanza in your package.json. This can be used to toggle on and off various parsing features.

We should also accept an `opts.configuration` option, which would take precedence. This would allow a library consuming `yargs-parser` to:

* load configuration from its own stanza.
* turn off feature toggling if this is not something they want in their own library.
* this still allows us to keep the default configuration loading behavior in `yargs-parser` and out of `yargs`.

**Comment by bcoe** [comment]
update based on discussion in #3 

* we'll now accept a configuration object as the only method for configuring `yargs-parser`.
* we'll pull the automated loading of a `yargs` stanza into `yargs` itself.

CC: @isaacs

**Comment by nexdrew** [comment]
I think this is smart. The API could support one big `opts` object:

```
var argv = require('yargs-parser')
  .config({
    'short-option-groups': false,
    'camel-case-expansion': false,
    'dot-notation': false,
    'parse-numbers': false,
    'boolean-negation': false
  })
  .parse(process.argv.splice(2))
```

Or individual config methods:

```
var argv = require('yargs-parser')
  .shortOptionGroups(false)
  .camelCaseExpansion(false)
  .dotNotation(false)
  .parseNumbers(false)
  .booleanNegation(false)
  .parse(process.argv.splice(2))
```

Or both!

**Comment by bcoe** [comment]
This is now possible :+1:
