### ISSUE TITLE
yargs converts numbers that start with 0x to decimals, even if parse-numbers if false

### ISSUE THREAD

**Issue by ghost** [yargs/yargs-parser#413]
I'd rather have it pass me the hex representation. Or maybe there is another option that does that?

**Comment by xiongemi** [comment]
i just tried, but change the 'parse-numbers' to false, it actually keeps the hex code and not convert it to numbers. i think it is fixed?

**Comment by shadowspawn** [comment]
Thanks @xiongemi 

Confirmed working with this code:
```js
const argv = require('yargs-parser')(process.argv.slice(2), { configuration: { 'parse-numbers': false }});
console.log(argv)
```

```console
% node index.js --number 0xABCD 0xabcd
{ _: [ '0xabcd' ], number: '0xABCD' }
```
