### ISSUE TITLE
Not working with single dash -

### ISSUE THREAD

**Issue by nabtron** [yargs/yargs-parser#417]
The code works fine when i use double dash with the argument flag, however it doesn't work as expected with single dash. 

I am using this code:

`    const argv = parser(message);
      console.log(argv);
`
Where message is: 

`!bot -data something
`

With `--data` it says:
{ _: [ '!bot' ], data: 'something' }

With `-data` it says:
`{ _: [ '!bot' ], d: true, a: [ true, 'something' ], t: true }`

Please guide if i am missing something. 

Thank you.

**Comment by shadowspawn** [comment]
By default yargs-parser supports short options like `-d` and long options like `--data`. Short options can be combined after a single dash, so `-abc` is interpreted like `-a` `-b` `-c`. This is fairly standard behaviour across utilities and command-line parsers.

There is a configuration option to change this behaviour, see: https://github.com/yargs/yargs-parser#short-option-groups

Way back when long options were first coming into use there were some utilities using single-dash and some using double-dash, but double-dash won and is far more common these days.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
