### ISSUE TITLE
Invalid transformation of upper camelcase fields

### ISSUE THREAD

**Issue by arcanis** [yargs/yargs-parser#54]
My config.json file contains the following:

```js
{
    "models": [ {
        "id": 42,
        "UserUid": "e40d18c5-ba1d-43f5-90a2-a8e45547ff94"
    } ]
}
```

However, when loaded via Yargs, I get the following:

```js
{
    "models": [ {
        "id": 42,
        "userUid": "e40d18c5-ba1d-43f5-90a2-a8e45547ff94"
    } ]
}
```

Notice how the `UserUid` has been changed into `userUid`, which breaks various pieces of code.

Of course, I could disable `camel-case-expansion`, but then I would lose the `--init-server` to `initServer` transform too, which I'd like to keep. Could it be possible to add an option to preserve the case of a word's first letter, so that upper camelcase strings would work just as well as lower camelcase strings ?

**Comment by nexdrew** [comment]
@arcanis Offhand I'm not able to reproduce the problem:

```js
var parse = require('yargs-parser')
var detailed = parse.detailed(process.argv.slice(2), {
  envPrefix: 'YP',
  config: 'config',
  alias: {
    config: ['c', 'con-fig']
  }
})
console.log('yargs-parser:', detailed.argv.models)

var argv = require('yargs')
  .env('YP')
  .config()
  .alias('config', ['c', 'con-fig'])
  .argv
console.log('       yargs:', argv.models)
```

```console
$ node yp-issue54.js --config yp-issue54.json
yargs-parser: [ { id: 42, UserUid: 'e40d18c5-ba1d-43f5-90a2-a8e45547ff94' } ]
       yargs: [ { id: 42, UserUid: 'e40d18c5-ba1d-43f5-90a2-a8e45547ff94' } ]

$ YP_CONFIG=yp-issue54.json node yp-issue54.js
yargs-parser: [ { id: 42, UserUid: 'e40d18c5-ba1d-43f5-90a2-a8e45547ff94' } ]
       yargs: [ { id: 42, UserUid: 'e40d18c5-ba1d-43f5-90a2-a8e45547ff94' } ]
```

How are you loading the config? Mind pasting or pointing to some code that demonstrates this?

**Comment by arcanis** [comment]
Sorry, I just double checked, and the issue was coming from a post-transform, not Yargs itself.. My bad :disappointed:

**Comment by nexdrew** [comment]
@arcanis No problem! Thanks for confirming, and thanks for using yargs!
