### ISSUE TITLE
Unexpected behavior when combining dot-notation and camel-case expansion

### ISSUE THREAD

**Issue by adius** [yargs/yargs-parser#77]
`--dot-notation.foo.bar` yields to

```js
{
  'dot-notation': {foo: {bar: true}},
  dotNotationFooBar: true,
}
```

I would, however, expect it to get parsed to:

```js
{
  'dot-notation': {foo: {bar: true}},
  dotNotation: {foo: {bar: true}},
}
```

Is this a bug or the supposed behavior?

**Comment by bcoe** [comment]
@adius this feels like a bug; if you get bored, would happily accept a patch 😉

**Comment by iilei** [comment]
May I help with the Patch?

**Comment by iilei** [comment]
Since the latest version this can be closed I suppose

**Comment by bcoe** [comment]
@adius this should be fixed now thanks to @iilei's great work 👍
