### ISSUE TITLE
Omit original key when camel cased key is added

### ISSUE THREAD

**Issue by rightaway** [yargs/yargs-parser#79]
In `node example.js --foo-bar`, it returns `{ _: [], 'foo-bar': true, fooBar: true }`. Can it return `{ _: [], fooBar: true }` because I do some external validation of the returned object to ensure that everything is right. And I would have to duplicate the validation for `fooBar` to `foo-bar`. It would be better if both weren't to appear in the returned object.

**Comment by bcoe** [comment]
@rightaway in your project, you should be able to add a `yargs` key to your package.json that disables camel-case expansion:

```json
{
  "yargs": {
     "camel-case-expansion": false
  }
}
```

If you only want one copy of the key, I recommend doing this and then applying the validation logic and camel-case logic in your application.

In my personal applications, I tend to _sometimes_ rely on the camel-case expansion, and sometimes not; I think it would break a lot of applications to implement this suggestion, and it's probably better to simply disable `camel-case` expansion for the use-case you're describing 👍 

Let me know if you bump into any issues configuring the parser.
