### ISSUE TITLE
Inconsistent array parsing(string values are wrapped in an array instead of parsed)

### ISSUE THREAD

**Issue by le0nik** [yargs/yargs-parser#82]
Original issue: https://github.com/yargs/yargs/issues/789.

The string values are parsed correctly in case of `boolean` or `number` values, but are not in case of array. Something like https://github.com/mccormicka/string-argv could be used to parse strings into arrays(simple parsing might not work because quotes must be considered, too).

Passed through cli:

```js
const argv = require('yargs')
  .options({
    arr: {
      type: 'array',
    },
  })
  .argv;

console.log('argv', argv);
```

`$ node ./test.js --arr foo bar`
Outputs: `argv { _: [], arr: [ 'foo', 'bar' ], '$0': 'test.js' }`

Passed through `.config()`

```js
const argv = require('yargs')
  .config({
    arr: 'foo bar',
  })
  .options({
    arr: {
      type: 'array',
    },
  })
  .argv;

console.log('argv', argv);
```

`$ node ./test.js`
Outputs: `argv { _: [], arr: [ 'foo bar' ], '$0': 'test.js' }`

yargs@6.6.0

**Comment by bcoe** [comment]
@le0nik thanks for opening this issue; we're playing catch up right now, but will work on getting to this ASAP!

**Comment by JaKXz** [comment]
Good news! I have a failing test around this (I think). PR coming soon!

**Comment by bcoe** [comment]
@le0nik @JaKXz having revisited this, my feeling is that this behavior is actually reasonable -- although we may want to document it somewhere?

My expectation with `.config` is that that the object passed would already have split arrays and objects out, so something like this:

```js
.config({
  foo: ["a", "b"],
  bar: {
     a: 99,
     b: 33
   }
})
```

This makes it easy to load a JSON configuration file of disk and use it to populate yargs. tldr; I don't think we should think of the values passed to `.config` as unparsed command line values, rather they're an intermediate JSON representation.
