### ISSUE TITLE
camelcase library causes uglify to fail

### ISSUE THREAD

**Issue by amcdnl** [yargs/yargs-parser#98]
The camelcase library is ES6. When you use this project with tools like Webpack and Uglify they throw errors because it can't parse the camelcase library.

**Comment by sindresorhus** [comment]
You have to use Babel first if you want to run this through Uglify. This applies to most Node.js modules.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
